language: android 
android: 
  components: 
    - tools 
    - platform-tools 
    - build-tools-26.0.2 
    - android-26 
    - extra-android-m2repository 
install:
  - bundle install
cache:
  - bundler
before_script:
  - bundle exec danger